export const tagTypes = {
  products: "products",
  categories: "categories",
  subCategories: "subCategories",
  brands: "brands",
  units: "units",
  variantAttributes: "variantAttributes",
  warranties: "warranties",
  manageStock: "manageStock",
  warehouse: "warehouse",
  store: "store",
  stockTransfers: "stockTransfers",
  payment: "payment",
  promo: "promo",
  expenseCategories: "expenseCategories",
  expenses: "expenses",
  suppliers: "suppliers",
  customers: "customers",
  employees: "employees",
  departments: "departments",
  designations: "designations",
  shifts: "shifts",
  attendance: "attendance",
};

export const tagTypesList = [
  tagTypes.products,
  tagTypes.categories,
  tagTypes.subCategories,
  tagTypes.brands,
  tagTypes.units,
  tagTypes.variantAttributes,
  tagTypes.warranties,
  tagTypes.manageStock,
  tagTypes.warehouse,
  tagTypes.store,
  tagTypes.stockTransfers,
  tagTypes.payment,
  tagTypes.promo,
  tagTypes.expenseCategories,
  tagTypes.expenses,
  tagTypes.suppliers,
  tagTypes.customers,
  tagTypes.employees,
  tagTypes.departments,
  tagTypes.designations,
  tagTypes.shifts,
  tagTypes.attendance,
];
