export const tagTypes = {
  users: "users",
  products: "products",
  categories: "categories",
  subCategories: "subCategories",
  brands: "brands",
  units: "units",
  variantAttributes: "variantAttributes",
  warranties: "warranties",
  manageStock: "manageStock",
  warehouse: "warehouse",
  store: "store",
  stockTransfers: "stockTransfers",
  payment: "payment",
  saleReturn: "saleReturn",
  purchase: "purchase",
  promo: "promo",
  expenseCategories: "expenseCategories",
  expenses: "expenses",
  suppliers: "suppliers",
  customers: "customers",
  employees: "employees",
  departments: "departments",
  designations: "designations",
  shifts: "shifts",
  attendance: "attendance",
  leaveType: "leaveType",
  leaveApply: "leaveApply",
  holidays: "holidays",
  payrolls: "payrolls",
  roles: "roles",
  bankAccount: "bankAccount",
  banIp: "banIp",
};

export const tagTypesList = [
  tagTypes.users,
  tagTypes.products,
  tagTypes.categories,
  tagTypes.subCategories,
  tagTypes.brands,
  tagTypes.units,
  tagTypes.variantAttributes,
  tagTypes.warranties,
  tagTypes.manageStock,
  tagTypes.warehouse,
  tagTypes.store,
  tagTypes.stockTransfers,
  tagTypes.payment,
  tagTypes.saleReturn,
  tagTypes.purchase,
  tagTypes.promo,
  tagTypes.expenseCategories,
  tagTypes.expenses,
  tagTypes.suppliers,
  tagTypes.customers,
  tagTypes.employees,
  tagTypes.departments,
  tagTypes.designations,
  tagTypes.shifts,
  tagTypes.attendance,
  tagTypes.leaveType,
  tagTypes.leaveApply,
  tagTypes.holidays,
  tagTypes.payrolls,
  tagTypes.roles,
  tagTypes.bankAccount,
  tagTypes.banIp,
];
